In [2]:
import pandas as pd

url = "https://raw.githubusercontent.com/dm8745342-lab/bmw-sales-data-analysis/refs/heads/main/data/bmw_global_sales_dataset.csv"
df = pd.read_csv(url)

print("Rows:", df.shape[0])
print("Columns:", df.shape[1])
print(df.columns.tolist())
df.head()

Rows: 1000
Columns: 14
['year', 'month', 'country', 'model', 'segment', 'engine_type', 'price_usd', 'marketing_spend_usd', 'dealership_count', 'fuel_price_usd', 'gdp_growth_percent', 'interest_rate_percent', 'competition_index', 'units_sold']

,year,month,country,model,segment,engine_type,price_usd,marketing_spend_usd,dealership_count,fuel_price_usd,gdp_growth_percent,interest_rate_percent,competition_index,units_sold
0,2021,1,Australia,X1,SUV,Petrol,82234,315372,96,0.97,6.29,1.2,8,324
1,2018,8,Australia,i4,Sedan,Electric,82291,447798,234,0.97,6.29,1.2,7,556
2,2022,12,USA,5 Series,Electric,Hybrid,40594,259755,25,0.97,6.29,1.2,7,152
3,2019,11,Australia,i7,SUV,Electric,42371,323541,319,0.97,6.29,1.2,5,730
4,2021,12,Brazil,X5,SUV,Diesel,82315,482015,367,0.97,6.29,1.2,2,1156

In [2]:
df.info()
print()
print(df.isnull().sum())
print()
print("Duplicates:", df.duplicated().sum())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 14 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   year                   1000 non-null   int64
 1   month                  1000 non-null   int64
 2   country                1000 non-null   object
 3   model                  1000 non-null   object
 4   segment                1000 non-null   object
 5   engine_type            1000 non-null   object
 6   price_usd              1000 non-null   int64
 7   marketing_spend_usd    1000 non-null   int64
 8   dealership_count       1000 non-null   int64
 9   fuel_price_usd         1000 non-null   float64
 10  gdp_growth_percent     1000 non-null   float64
 11  interest_rate_percent  1000 non-null   float64
 12  competition_index      1000 non-null   int64
 13  units_sold             1000 non-null   int64
dtypes: float64(3), int64(7), object(4)
memory usage: 109.5+ KB

year                     0
month                    0
country                  0
model                    0
segment                  0
engine_type              0
price_usd                0
marketing_spend_usd      0
dealership_count         0
fuel_price_usd           0
gdp_growth_percent       0
interest_rate_percent    0
competition_index        0
units_sold               0
dtype: int64

Duplicates: 0

                         dtype  nulls  unique_values
year                     int64      0             10
month                    int64      0             12
country                 object      0             10
model                   object      0             10
segment                 object      0              3
engine_type             object      0              4
price_usd                int64      0            994
marketing_spend_usd      int64      0            996
dealership_count         int64      0            355
fuel_price_usd         float64      0              1
gdp_growth_percent     float64      0              1
interest_rate_percent  float64      0              1
competition_index        int64      0             10
units_sold               int64      0            621

In [3]:
print("Duplicates:", df.duplicated().sum())
print("Years:", df["year"].min(), "to", df["year"].max())
print(df["country"].unique())
print(df["segment"].unique())
print(df["engine_type"].unique())

Duplicates: 0
Years: 2015 to 2024
['Australia' 'USA' 'Brazil' 'China' 'India' 'UK' 'Canada' 'Germany'
 'France' 'Japan']
['SUV' 'Sedan' 'Electric']
['Petrol' 'Electric' 'Hybrid' 'Diesel']